spring:
  application:
    name: monad

server:
  port: 8080

jwt:
  secret: bW9uYWQtand0LXNlY3JldC1rZXktZm9yLWRldmVsb3BtZW50LW9ubHktMjAyNg==
  access-token-expiry: 1800000
  refresh-token-expiry: 604800000
